name: Build templates

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build templates
      run: |
        sh build.sh
    - name: Upload Vannila-Purpur-latest.tar.zst
      uses: actions/upload-artifact@v3
      with:
        name: Vannila-Purpur-latest.tar.zst
        path: Vannila-Purpur-latest.tar.zst
