name: Build templates
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  job_1:
    name: build Vannila-Purpur-latest
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
            sh build.sh
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: Vannila-Purpur-latest
          path: Vannila-Purpur-latest.tar.zst
